define(["brease"], function({core:{designer:{BaseWidget:{ClassInfo:s}}}}, e) {const classInfo={meta:{className:"widgets.mapp6D.Assembly6D",parents:["*"],children:[],inheritance:["widgets.mapp6D.Assembly6D","brease.core.BaseWidget"],creator:"1b67874419e44330ac74618da9668d44",eventBindingApi:function (w) {
function a(e, f) { w.addServerEventListener(e, f); }
function c(...args) { const [{ action: a }] = args.slice(-1); return w[a](...args); }
return {
click: f => a('Click', f),
disabledClick: f => a('DisabledClick', f),
enableChanged: f => a('EnableChanged', f),
focusIn: f => a('FocusIn', f),
focusOut: f => a('FocusOut', f),
visibleChanged: f => a('VisibleChanged', f),
focus: function () { c({ origin: 'action', action: 'focus' }); },
setEnable: function (a1) { c(a1,{ origin: 'action', action: 'setEnable' }); w.sendValueChange({enable: w.getEnable()}, false);},
setStyle: function (a1) { c(a1,{ origin: 'action', action: 'setStyle' }); w.sendValueChange({style: w.getStyle()}, false);},
setVisible: function (a1) { c(a1,{ origin: 'action', action: 'setVisible' }); w.sendValueChange({visible: w.getVisible()}, false);},
showTooltip: function () { c({ origin: 'action', action: 'showTooltip' }); }
};
},actions:{"Focus":{"method":"focus"},"setAdditionalStyle":{"method":"setAdditionalStyle","parameter":{"styleName":{"name":"styleName","index":0,"type":"StyleReference"}}},"setEditable":{"method":"setEditable","parameter":{"editable":{"name":"editable","index":0,"type":"Boolean"},"metaData":{"name":"metaData","index":1,"type":"Object"}}},"SetEnable":{"method":"setEnable","parameter":{"value":{"name":"value","index":0,"type":"Boolean"}}},"setMpLink":{"method":"setMpLink","parameter":{"mpLink":{"name":"mpLink","index":0,"type":"MpComIdentReference"}}},"setMpLinkTrafficManager":{"method":"setMpLinkTrafficManager","parameter":{"mpLinkTrafficManager":{"name":"mpLinkTrafficManager","index":0,"type":"MpComIdentReference"}}},"setParentCoWiId":{"method":"setParentCoWiId","parameter":{"value":{"name":"value","index":0,"type":"String"}}},"setShowAdditionalShuttleInfo":{"method":"setShowAdditionalShuttleInfo","parameter":{"showAdditionalShuttleInfo":{"name":"showAdditionalShuttleInfo","index":0,"type":"Boolean"}}},"setShowAdditionalTrafficManagerInfo":{"method":"setShowAdditionalTrafficManagerInfo","parameter":{"showAdditionalTrafficManagerInfo":{"name":"showAdditionalTrafficManagerInfo","index":0,"type":"Boolean"}}},"setShowCoordinateSystem":{"method":"setShowCoordinateSystem","parameter":{"showCoordinateSystem":{"name":"showCoordinateSystem","index":0,"type":"Boolean"}}},"setShowRxAxisShuttleInfo":{"method":"setShowRxAxisShuttleInfo","parameter":{"showRxAxisShuttleInfo":{"name":"showRxAxisShuttleInfo","index":0,"type":"Boolean"}}},"setShowRyAxisShuttleInfo":{"method":"setShowRyAxisShuttleInfo","parameter":{"showRyAxisShuttleInfo":{"name":"showRyAxisShuttleInfo","index":0,"type":"Boolean"}}},"setShowRzAxisShuttleInfo":{"method":"setShowRzAxisShuttleInfo","parameter":{"showRzAxisShuttleInfo":{"name":"showRzAxisShuttleInfo","index":0,"type":"Boolean"}}},"setShowXAxisShuttleInfo":{"method":"setShowXAxisShuttleInfo","parameter":{"showXAxisShuttleInfo":{"name":"showXAxisShuttleInfo","index":0,"type":"Boolean"}}},"setShowYAxisShuttleInfo":{"method":"setShowYAxisShuttleInfo","parameter":{"showYAxisShuttleInfo":{"name":"showYAxisShuttleInfo","index":0,"type":"Boolean"}}},"setShowZAxisShuttleInfo":{"method":"setShowZAxisShuttleInfo","parameter":{"showZAxisShuttleInfo":{"name":"showZAxisShuttleInfo","index":0,"type":"Boolean"}}},"SetStyle":{"method":"setStyle","parameter":{"value":{"name":"value","index":0,"type":"StyleReference"}}},"setTabIndex":{"method":"setTabIndex","parameter":{"value":{"name":"value","index":0,"type":"Number"}}},"SetVisible":{"method":"setVisible","parameter":{"value":{"name":"value","index":0,"type":"Boolean"}}},"ShowTooltip":{"method":"showTooltip"}},properties:{}}};if(s.classExtension) {classInfo.classExtension = s.classExtension;}if(e) {classInfo.classExtension = e;}return classInfo;});
