
ACTION config: 
	gAcp6DCtrl.Status.Ready := FALSE;
	gameBrain.showHMIButton := FALSE;
	enableButtons := TRUE;
	
	shuttleStartupInfo[0].initXPos := 0.060;
	shuttleStartupInfo[0].initYPos := 0.060;
	shuttleStartupInfo[1].initXPos := 0.180;
	shuttleStartupInfo[1].initYPos := 0.180;
	shuttleStartupInfo[2].initXPos := 0.300;
	shuttleStartupInfo[2].initYPos := 0.060;
	shuttleStartupInfo[3].initXPos := 0.420;
	shuttleStartupInfo[3].initYPos := 0.180;

END_ACTION
